sudo: false
language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  global:
    - MONGO_VERSION=stable
    - DRIVER_VERSION="stable"


services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mediainfo
      - libav-tools
      - libavcodec-extra-53

install:
  - composer self-update
  - php -i
  - composer install
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then yes '' | pecl -q install -f mongo-${DRIVER_VERSION}; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then pecl install -f mongodb-${DRIVER_VERSION}; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then composer require "alcaeus/mongo-php-adapter=${ADAPTER_VERSION}" --ignore-platform-reqs; fi


script:
    - find src -type f -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
    - php app/console lint:yaml src
    - php app/console lint:yaml app
    - php app/console lint:twig src
    - php app/console lint:twig app
    - ./bin/travis_checks/check_var_dumps
    - php bin/php-cs-fixer.phar fix src --level=symfony --dry-run -v
    - phpunit -c app
