sudo: false
language: php

php:
  - 7.1

env:
  - MONGO_VERSION=stable

services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mediainfo
      - libav-tools
      - libavcodec-extra-53

before_script:
  - composer self-update
  - php -i
  - composer install --ignore-platform-reqs --no-scripts


script:
    - curl -L -O https://github.com/phpstan/phpstan/releases/download/0.7/phpstan-0.7.phar
    - php phpstan-0.7.phar analyse src/
