sudo: false
language: php

php:
  - 5.5
  - 5.6

env:
  - MONGO_VERSION=stable

services:
  - mongodb
  - docker

addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mediainfo
      - libav-tools
      - libavcodec-extra-53

before_script:
  - yes '' | pecl -q install -f mongo-${MONGO_VERSION}
  - composer self-update
  - php -i
  - composer install
  - docker pull phpstan/phpstan
  - docker run --rm -v src/Pumukit:/app phpstan/phpstan analyse / --level=5

script:
    - find src -type f -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
    - php app/console lint:yaml src
    - php app/console lint:yaml app
    - php app/console lint:twig src
    - php app/console lint:twig app
    - ./bin/travis_checks/check_var_dumps
    - php bin/php-cs-fixer.phar fix src --level=symfony --dry-run -v
    - phpunit -c app
