sudo: false
language: php
dist: trusty

php:
  - 5.5
  - 5.6

env:
  - MONGO_VERSION=stable

services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mediainfo
      - libav-tools
      - libavcodec-extra-54

before_script:
  - yes '' | pecl -q install -f mongo-${MONGO_VERSION}
  - composer self-update
  - php -i
  - composer install


script:
    - find src -type f -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
    - php app/console lint:yaml src
    - php app/console lint:yaml app
    - php app/console lint:twig src
    - php app/console lint:twig app
    - ./bin/travis_checks/check_var_dumps
    - php bin/php-cs-fixer.phar fix --level=symfony --dry-run -v src
    - php bin/phpunit -c app
